// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package register

import (
	"gorm.io/gorm"
	"online-course.mifwar.com/internal/register/delivery/http"
	register2 "online-course.mifwar.com/internal/register/usecase"
	"online-course.mifwar.com/internal/user/repository"
	user2 "online-course.mifwar.com/internal/user/usecase"
	"online-course.mifwar.com/pkg/mail/sendgrid"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *register.RegisterHandler {
	userRepository := user.NewUserRepository(db)
	userUseCase := user2.NewUserUseCase(userRepository)
	mailMail := mail.NewMail()
	registerUseCase := register2.NewRegisterUseCase(userUseCase, mailMail)
	registerHandler := register.NewRegisterHandler(registerUseCase)
	return registerHandler
}
